In [ ]:
# numpy is used to do scientific calculations.
#elements of same datatype in the form of array
#memory consume less as compare to listes
#computtation power is more than lists
#numpy is a built-in library which is fast as compare to lists
#homogeneous elements stored in array whereas list stores heterogeneous elements

# One Dimensional Array

In [2]:
import numpy as np
a = [1,2,3,4,5] 
b = np.array(a) 
b

array([1, 2, 3, 4, 5])

In [2]:
a=[]
size= int(input("Enter size:"))
for i in range(size):
    val=int(input("Enter item:"))
    a.append(val)
b=np.array(a)
b

Enter size:4
Enter item:67
Enter item:89
Enter item:54
Enter item:23


array([67, 89, 54, 23])

# Two dimensional array 

In [3]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]] 
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# How can we check shape and size of an array?

In [3]:
a=np.array([1,34,89,9900])
a

array([   1,   34,   89, 9900])

In [4]:
print("Total Shape=",a.shape)
print("Total Elements = ",a.size)

Total Shape= (4,)
Total Elements =  4


In [5]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print("Total Shape=",b.shape)
print("Total Elements = ",b.size)
print("Total Dimensions :" , b.ndim) 

Total Shape= (3, 3)
Total Elements =  9
Total Dimensions : 2


In [7]:
#images-> pixels(0-255) -> 0px black, 255px white -> normalize(0-1)px
#imitially weights -> 0,1
#optimization techniques-> 0,1
#matrix-> n(rows), n(columns)
#symmatric matrix -> n(rows) = n(columns)
#aysymmatric matrix -> n(rows) != n(columns)

# Numpy Predefined Functions

In [12]:
#1.) zeros() function-> This function create an array (either one dimensional or multi dimensional) and fill all the values with zeros.
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [13]:
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
b.ndim

2

In [15]:
a.ndim

1

In [10]:
#2.) ones() function-> This function creats an array (either one dimensional or multi dimensional) and fill all the values with ones .
a=np.ones(3)
a

array([1., 1., 1.])

In [11]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
type(a)

numpy.ndarray

In [13]:
a.shape

(2, 3)

In [14]:
a.size

6

In [15]:
#3.) eye() function-> This function creats an array with all the digonal elements as 1 and rest are 0(In square matrix). In non-square matrix the value are still one for digonal (upto which it can draw digonal ) and rest are zero, by default this funtion is 2D.

a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
#4.) diag()-> This function creates a two dimensional array with all the diagonal eelements as the given value and rest are 0.
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [18]:
#5.) randint()-> This function is used to generate a random numbers between a given range.
#syntax: randint(min_value, max_value, total_numbers)
a=np.random.randint(1,10,4)
a

array([4, 5, 2, 1])

In [19]:
#6.) rand()-> This function is used to generate a random number between 0 and 1.
#syntax: rand(number of values)
a=np.random.rand(5)
a

array([0.02887913, 0.13245514, 0.15204705, 0.11870434, 0.43676388])

In [20]:
#7.) randn()-> This function is used to generate a random number from -3 to close 3. This may return positive or negative numbers as well.
#syntax: random.randn(number of values)
a=np.random.randn(5)
a

array([-0.849144  ,  0.9777132 ,  1.70925495,  0.04208776, -0.14985008])

# Reshaping Data

In [21]:
a=np.random.randint(1,50,12)
a

array([44, 18, 38,  2, 49, 20, 47, 19, 43, 46, 42, 22])

In [22]:
# n(rows) * n(columns) = n(total_elements)

In [23]:
a.shape

(12,)

In [24]:
a=a.reshape(2,6)
a

array([[44, 18, 38,  2, 49, 20],
       [47, 19, 43, 46, 42, 22]])

In [25]:
a=a.reshape(6,2)
a

array([[44, 18],
       [38,  2],
       [49, 20],
       [47, 19],
       [43, 46],
       [42, 22]])

In [26]:
a=a.reshape(3,4)
a

array([[44, 18, 38,  2],
       [49, 20, 47, 19],
       [43, 46, 42, 22]])

In [27]:
a=a.reshape(4,3)
a

array([[44, 18, 38],
       [ 2, 49, 20],
       [47, 19, 43],
       [46, 42, 22]])

In [28]:
a=a.reshape(12,1)
a

array([[44],
       [18],
       [38],
       [ 2],
       [49],
       [20],
       [47],
       [19],
       [43],
       [46],
       [42],
       [22]])

In [29]:
a=a.reshape(1,12)
a

array([[44, 18, 38,  2, 49, 20, 47, 19, 43, 46, 42, 22]])

# Principle of -1

In [30]:
a=a.reshape(-1,4)
a

array([[44, 18, 38,  2],
       [49, 20, 47, 19],
       [43, 46, 42, 22]])

In [31]:
# Seed Function() ==> We know that randint dunction generates randon numbers. Everytime we run  the program, new set of random number is generated. So to solve this problem we will use seed() function.
np.random.seed(5)
a=np.random.randint(1,100,10)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [16]:
np.random.seed(111)
a = np.random.randint(1,500,30).reshape(6,5) 
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [32]:
#View vs Copy ==> When we slice a sub-array from an array, it may be done by two ways.
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [33]:
#Copy
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [35]:
b

array([0, 0, 0])

# Conditional Selection

In [36]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [38]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [39]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [41]:
print(a[a%2==0])

[ 2  4  6  8 10 12 14]


# Operations on Array

In [42]:
a=[1,2,3,4]
a*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [43]:
b=np.array(a)
b*2

array([2, 4, 6, 8])

In [44]:
a=np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [45]:
a+2

array([3, 4, 5, 6])

In [46]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [47]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [48]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [49]:
a+b

array([[ 6,  8],
       [10, 12]])

In [50]:
b-a

array([[4, 4],
       [4, 4]])

In [51]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [52]:
a*b

array([[ 5, 12],
       [21, 32]])

In [53]:
a.dot(b)

array([[19, 22],
       [43, 50]])

# Some more important numpy functions

In [55]:
a=np.array([10,20,30,40,50])
np.min(a)

10

In [56]:
np.max(a)

50

In [57]:
np.argmin(a)

0

In [58]:
np.argmax(a)

4

In [59]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [60]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [62]:
# Linespace()-> This function return value between a given range and with a same gap between consecutive elements.
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [68]:
np.random.seed(122)
a=np.random.randint(1,21,9).reshape(3,3)
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [69]:
np.sum(a)

116

In [70]:
np.sum(a,axis=1)

array([40, 46, 30])

In [71]:
np.min(a)

3

In [72]:
np.max(a)

17

In [73]:
np.cumsum(a)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

In [74]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [18]:
# np.unique(arr, return_index=True, return_counts=True)
# returns 3 array . 1 . the array with unique values . 2 . the array with respective index value . 3 . the array with counting of frequencey .
a = np.array([10,20,30,40,10,20,50]) 
np.unique(a, return_index=True, return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [64]:
#horizontal and vertical stacking
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [65]:
b

array([5, 6, 7, 8])

In [66]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])